version: '3.9'
services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: your_mysql_password  # Replace with your password
      MYSQL_DATABASE: staff_portal_back_test
    ports:
      - "3307:3306"

  web:
    build: .
    ports:
      - "3010:3010"
    depends_on:
      - mysql
    environment:
      RAILS_MASTER_KEY: your_master_key # Replace with your key
      MYSQL_PASSWORD: your_mysql_password # Replace with your password
    command: bash -c "bundle exec rails db:setup && tail -f log/development.log"
