---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/login":
    post:
      summary: ログイン
      tags:
      - Authentication
      parameters: []
      responses:
        '200':
          description: ログイン成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                  username:
                    type: string
        '401':
          description: 認証失敗
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Invalid email or password
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  example: user@example.com
                password:
                  type: string
                  example: password123
              required:
              - email
              - password
  "/api/v1/logout":
    delete:
      summary: ログアウト
      tags:
      - Authentication
      security:
      - bearerAuth: []
      responses:
        '204':
          description: ログアウト成功
        '401':
          description: 認証エラー
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
