name: Rails CI

on:
  push:
    branches: ["main", "develop"]
  pull_request:
    branches: ["main", "develop"]

env:
  RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
  MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # リポジトリをチェックアウト
      - name: Check out repository
        uses: actions/checkout@v3

      # 必要なパッケージのインストール
      - name: Install MySQL
        run: |
          sudo apt-get update
          sudo apt-get install -y mysql-server mysql-client

      # MySQLサーバーの設定と起動
      - name: Start and configure MySQL
        run: |
          sudo systemctl start mysql
          sudo mysql -u root -e "ALTER USER 'root'@'localhost' IDENTIFIED WITH 'mysql_native_password' BY '$MYSQL_PASSWORD'; FLUSH PRIVILEGES;"
          sleep 5 # パスワード変更の反映を待つ
          sudo mysql -u root -p"$MYSQL_PASSWORD" -e "CREATE DATABASE IF NOT EXISTS staff_portal_back_test;"
        env:
          MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}

      # Rubyのセットアップ
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.3

      # Bundler & gems のインストール
      - name: Install gems
        run: |
          gem install bundler
          bundle install

      # DBの作成とマイグレーション
      - name: Database setup
        run: |
          bundle exec rails db:create
          bundle exec rails db:migrate

      # テストの実行
      - name: Run tests
        run: bundle exec rails test

      # Lint チェック
      - name: RuboCop
        run: bundle exec rubocop
