name: Rails CI

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # リポジトリをチェックアウト
      - name: Check out repository
        uses: actions/checkout@v3

      # Ruby をセットアップ（例えば 3.2.x）
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2

      # データベース（PostgreSQLなど）をセットアップ（不要なら削除）
      - name: Configure DB
        run: sudo service postgresql start

      # キャッシュを活用（bundle installの高速化）
      - name: Bundle cache
        uses: actions/cache@v3
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-bundle-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: ${{ runner.os }}-bundle-

      # gem のインストール
      - name: Install gems
        run: bundle install --jobs 4 --path vendor/bundle

      # DB作成・マイグレーション（RDBを使う場合）
      - name: Setup DB
        run: |
          cp config/database.yml.ci config/database.yml  # CI用DB設定ファイルをコピーする例
          rails db:create
          rails db:migrate

      # RSpecなどでテストを実行
      - name: Run tests
        run: |
          bundle exec rails test   # Minitest
          # bundle exec rspec      # RSpecの場合

      # Lint / Style Check（Rubocopなど）
      - name: RuboCop
        run: bundle exec rubocop
