name: Rails CI

on:
  push:
    branches: ["main", "develop"]
  pull_request:
    branches: ["main", "develop"]

env:
  RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
  MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}


jobs:
  build-and-test:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
          MYSQL_DATABASE: staff_portal_back_test
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=5

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.3

      - name: Install gems
        run: |
          gem install bundler
          bundle config set --local without 'development'
          bundle install


      - name: Validate Rails Master Key (after bundle install)  # KEY CHANGE
        run: |
          echo "Validating RAILS_MASTER_KEY length..."
          if [[ $(echo -n "$RAILS_MASTER_KEY" | wc -c) -ne 32 ]]; then
            echo "Error: RAILS_MASTER_KEY must be 32 characters (16 bytes) long."
            exit 1
          fi
          echo "RAILS_MASTER_KEY length is valid."

      - name: Install docker-compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose
      - name: Build Docker image without cache
        run: docker-compose build --no-cache
      - name: Database setup
        run: bundle exec rails db:setup

      - name: Database setup
        env:
           DATABASE_HOST: localhost
           CI: true
        run: bundle exec rails db:setup

      - name: Run tests
        run: bundle exec rails test

      - name: RuboCop
        run: bundle exec rubocop
