name: Rails CI

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

env:
  RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
  MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # リポジトリをチェックアウト
      - name: Check out repository
        uses: actions/checkout@v3

      # Ruby をセットアップ
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.3

      # MySQL サーバーをセットアップ
      - name: Install MySQL server
        run: |
          sudo apt-get update
          sudo apt-get install -y mysql-server mysql-client

      # 必要なディレクトリを作成
      - name: Create MySQL run directory
        run: |
          sudo mkdir -p /var/run/mysqld
          sudo chown mysql:mysql /var/run/mysqld

      # MySQLをセーフモードで起動してrootパスワードをリセット
      - name: Configure MySQL
        run: |
          sudo systemctl stop mysql
          sudo mysqld_safe --skip-grant-tables &
          sleep 5

          mysql -u root -e "FLUSH PRIVILEGES; ALTER USER 'root'@'localhost' IDENTIFIED BY '${{ secrets.MYSQL_PASSWORD }}';"

          sudo killall mysqld
          sudo systemctl start mysql

      # テスト用データベースを作成
      - name: Create test database
        run: |
          mysql -u root -p${{ secrets.MYSQL_PASSWORD }} -e "CREATE DATABASE IF NOT EXISTS staff_portal_back_test;"

      # キャッシュを活用（bundle installの高速化）
      - name: Bundle cache
        uses: actions/cache@v3
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-bundle-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: ${{ runner.os }}-bundle-

      # Bundler & gems のインストール
      - name: Install gems
        run: |
          gem install bundler
          bundle install

      # DB作成・マイグレーション
      - name: Create DB
        env:
          DATABASE_URL: "mysql2://root:${{ secrets.MYSQL_PASSWORD }}@127.0.0.1:3306/staff_portal_back_test"
        run: bundle exec rails db:create

      - name: Migrate DB
        env:
          DATABASE_URL: "mysql2://root:${{ secrets.MYSQL_PASSWORD }}@127.0.0.1:3306/staff_portal_back_test"
        run: bundle exec rails db:migrate

      # テストの実行
      - name: Run tests
        env:
          DATABASE_URL: "mysql2://root:${{ secrets.MYSQL_PASSWORD }}@127.0.0.1:3306/staff_portal_back_test"
        run: bundle exec rails test

      # Lint / Style Check
      - name: RuboCop
        run: bundle exec rubocop
