name: Rails CI

on:
  push:
    branches: ["main", "develop"]
  pull_request:
    branches: ["main", "develop"]

env:
  RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
  MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # リポジトリをチェックアウト
      - name: Check out repository
        uses: actions/checkout@v3

      # 必要なパッケージのインストール
      - name: Install MySQL 8.0
        run: |
          sudo apt-get update
          
          # リポジトリ設定の削除
          sudo rm -f /etc/apt/sources.list.d/mysql.list
          
          # キャッシュの削除
          sudo rm -rf /var/lib/apt/lists/*
          
          # リポジトリの追加
          wget https://dev.mysql.com/get/mysql-apt-config_0.8.29-1_all.deb
          sudo dpkg -i mysql-apt-config_0.8.29-1_all.deb
          sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys B7B3B788A8D3785C
         
          # リポジトリURLをhttpsで指定
          sudo sed -i 's|http://repo.mysql.com/apt/ubuntu|https://repo.mysql.com/apt/ubuntu|g' /etc/apt/sources.list.d/mysql.list
          
          sudo apt-get update
          sudo apt-get install -y mysql-server mysql-client

      # MySQLサーバーの設定と起動
      - name: Start and configure MySQL 8.0
        run: |
          sudo systemctl start mysql
          sleep 10 # MySQL起動完了を待機

          # MySQL設定ファイルの編集
          if [ -f /etc/mysql/my.cnf ]; then
              sudo sed -i 's/^bind-address\s*=\s*127.0.0.1/bind-address = 0.0.0.0/' /etc/mysql/my.cnf
              sudo sed -i 's/#default-authentication-plugin=mysql_native_password/default-authentication-plugin=mysql_native_password/' /etc/mysql/my.cnf
          fi
          
          # MySQL再起動
          sudo systemctl restart mysql
          sleep 10

          # MySQLの初期設定
          sudo mysql -u root -e "ALTER USER root@'%' IDENTIFIED WITH mysql_native_password BY '$MYSQL_PASSWORD'; FLUSH PRIVILEGES;"
          sudo mysql -u root -e "ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY '$MYSQL_PASSWORD'; FLUSH PRIVILEGES;"
          sleep 10
          echo "MYSQL_PASSWORD is: $MYSQL_PASSWORD"

           # MySQLが起動しているか確認
          sudo mysqladmin ping
          # パスワードなしで接続できるか確認
          sudo -u root -E mysql -u root -e "SELECT 1;"
          # パスワードありで接続できるか確認
          sudo -u root -E mysql -h localhost -u root -p"$MYSQL_PASSWORD" -e "CREATE DATABASE IF NOT EXISTS staff_portal_back_test;"
        env:
          MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}

      # Rubyのセットアップ
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.3

      # Bundler & gems のインストール
      - name: Install gems
        run: |
          gem install bundler
          bundle install

      # DBの作成とマイグレーション
      - name: Database setup
        run: |
          bundle exec rails db:create
          bundle exec rails db:migrate

      # テストの実行
      - name: Run tests
        run: bundle exec rails test

      # Lint チェック
      - name: RuboCop
        run: bundle exec rubocop
