name: Rails CI

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

env:
  RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # リポジトリをチェックアウト
      - name: Check out repository
        uses: actions/checkout@v3

      # Ruby をセットアップ
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.3

      # MySQL サーバーのインストールと設定
      - name: Install MySQL
        run: sudo apt-get update && sudo apt-get install -y mysql-server mysql-client

      - name: Configure MySQL
        run: |
          sudo mkdir -p /opt/homebrew/var/mysql
          sudo systemctl start mysql
          sudo mysql -e "CREATE USER 'root'@'localhost' IDENTIFIED BY '';"
          sudo mysql -e "GRANT ALL PRIVILEGES ON *.* TO 'root'@'localhost';"
          sudo mysql -e "FLUSH PRIVILEGES;"

      # MySQL ソケット指定で DB 作成
      - name: Create and Migrate Database
        run: |
          echo "Setting up database..."
          bundle exec rails db:create RAILS_ENV=test
          bundle exec rails db:migrate RAILS_ENV=test
        env:
          DB_SOCKET: /opt/homebrew/var/mysql/mysql.sock

      # テストの実行
      - name: Run Tests
        run: bundle exec rails test

      # Lint チェック
      - name: RuboCop
        run: bundle exec rubocop
